### ISSUE TITLE
[피드백]

### ISSUE THREAD

**Issue by 0xfmc** [samsunghappytree123/discordpy-bot#1]
강의에 대해 피드백을 해주세요! 더 좋은 강의를 만들어나갑니다!
사랑해 삼성해피트리!

**Comment by samsunghappytree123** [comment]
ㅋ

**Comment by samsunghappytree123** [comment]
고맙다... 그리고 이 이슈는 닫을께^^

**Comment by yangseunghyeon** [comment]
ㅋ

**Comment by yangseunghyeon** [comment]
와 전화 차다함?

**Comment by samsunghappytree123** [comment]
@yangseunghyeon 축하한다 전화 끊은거다

**Comment by samsunghappytree123** [comment]
![42619797-B0FF-4904-81C4-BCCCF4D4E210](https://user-images.githubusercontent.com/58595445/85200252-c6015680-b330-11ea-8f0f-c3ee7a086be3.png) @yangseunghyeon

**Comment by yangseunghyeon** [comment]
한명씩 인터뷰중이었는데

**Comment by 0xfmc** [comment]
ㅋㅋㅋ

**Comment by dfdddfd** [comment]
ㅘ!

**Comment by dfdddfd** [comment]
참고로 나 WHAT ARE YOU임

**Comment by ditto7890** [comment]
.

**Comment by dfdddfd** [comment]
???: 뿌에ㅔㅔㅔㅔㅔㅔㅔ엑

**Comment by 0xfmc** [comment]
![image](https://user-images.githubusercontent.com/45954870/85245827-c2caaf80-b483-11ea-959f-8d41019bd88d.png)

**Comment by 0xfmc** [comment]
갑질논란
홍보숲코듴ㅋㅋㅋㅋ

**Comment by samsunghappytree123** [comment]
@0xfmc 중요한거는 깃헙 아직 삭제 안함 ㅋㅋㅋ 삭제 안했다고 전해두세요.

**Comment by ditto7890** [comment]
.

**Comment by ditto7890** [comment]
![heuk](https://user-images.githubusercontent.com/59792804/85267860-ba3c9e00-b4b0-11ea-923d-9ec696450ccc.png)

**Comment by yangseunghyeon** [comment]
저거 주지마셈

**Comment by samsunghappytree123** [comment]
@yangseunghyeon 뭔소리임?

**Comment by yangseunghyeon** [comment]
코드말한거임

**Comment by yangseunghyeon** [comment]
ㅋㅋ루

**Comment by samsunghappytree123** [comment]
ㅋㅋㅋㅋ
